name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'Docker image tag to pull'
        required: true
        default: 'latest'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Pull Docker image
      run: |
        docker pull docker.io/${{ secrets.REGISTRY_USERNAME }}/petclinic-app:${{ inputs.docker_image_tag }}

    - name: Run container
      run: |
        docker run -d --name petclinic-app -p 8080:8080 docker.io/${{ secrets.REGISTRY_USERNAME }}/petclinic-app:${{ github.event.inputs.image_tag }}

    - name: Wait for application to start
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:8080; then
            echo "App is reachable!"
            exit 0
          else
            echo "Waiting for app..."
            sleep 5
          fi
        done
        echo "App did not become ready in time." >&2
        exit 1
    
    - name: Stop container
      if: always()
      run: |
        docker stop petclinic-app 
        docker rm petclinic-app 